---

- name: galaxy.cis
  src: https://github.com/MindPointGroup/RHEL7-CIS.git

- name: galaxy.fail2ban
  src: https://github.com/resmo/ansible-role-fail2ban.git

- name: galaxy.sshd
  src: https://github.com/willfarrell/ansible-role-sshd.git

