#!/usr/bin/env bash
set -e

ORG_ID=f4rr3ll

# pip install --upgrade ansible
# pip install --upgrade boto3
# pip install --upgrade --user awscli

# install deps
#ansible-galaxy install --roles-path=./roles -r requirements.yml

# Decrypt
#ansible-vault decrypt group_vars/all/secrets.yml --vault-password-file ~/.vault_password_f4rr3ll

# Encrypt
#ansible-vault encrypt group_vars/all/secrets.yml --vault-password-file ~/.vault_password_f4rr3ll

# Cloud
#ansible-playbook 1_aws.yml --vault-password-file ~/.vault_password_${ORG_ID}

# Servers
ansible bastion -m ping

ansible-playbook 2_servers.yml --vault-password-file ~/.vault_password_${ORG_ID}

